name: Deploy to neocities

# only run on changes to main
on:
  push:
    branches:
      - main

concurrency: # prevent concurrent deploys doing strange things
  group: deploy-to-neocities
  cancel-in-progress: true



jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Build and test
    steps:
      - uses: actions/checkout@v4
      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: Use NPM
        uses: bahmutov/npm-install@v1
      - name: Install dependencies & build
        run: npm i
              gatsby build
        working-directory: /home/runner/work/field-notes/public
      - name: Deploy to neocities
        uses: bcomnes/deploy-to-neocities@v1
        with:
          api_token: ${{ secrets.NEOCITIES_API_KEY }}
          cleanup: true
          dist_dir: public
